### ISSUE TITLE
Memory limits the size of strings the program can read.

### ISSUE THREAD

**Issue by henu** [henu/bigjson#1]
Code String class.

**Comment by changeling** [comment]
Code cannot read _any_ strings of _any_ size? Is this a real bug, and is it still open? Isn't that kind of the entire point of the library?

**Comment by henu** [comment]
Uhh... I mean, it can read as big strings as fits to your memory, but not bigger than that. Sorry for the bad issue title, I just wrote it quickly for myself, as I didn't expect any other person to ever read these :D

**Comment by changeling** [comment]
So, by strings, do you mean lines, or the values in a given key, like really big float precisions, or keys that hold huge chunks as their data, or do you mean the whole JSON structure? I'm assuming it isn't the latter, because, well... that seems like the whole point here. :)

**Comment by henu** [comment]
String values and string keys. Arrays, objects and the whole JSON file can still be arbitrary big.
