### ISSUE TITLE
Error iterating valid JSON file

### ISSUE THREAD

**Issue by robert-phe** [henu/bigjson#11]
`Exception(u'Unexpected bytes!')` is raised while parsing a valid JSON file.
```
f = open('test.json', 'rb')
bj = bigjson.load(f, 'utf-8')
for obj in bj:
    print(obj.to_python())
```
[test.json.zip](https://github.com/henu/bigjson/files/4590855/test.json.zip)

**Comment by henu** [comment]
The issue should be fixed now.

BTW can I use your test data to write and publish a test?
