### ISSUE TITLE
The parsed structure of wikidata

### ISSUE THREAD

**Issue by jackyys** [henu/bigjson#12]
Thanks a lot for your code.

Hi, I'm using your package to load the huge wikidata file "latest-all.json", which is about 1TB. It works fine during the loading part. However, it seems that the structure we get is different from the original wikidata structure. For instance, after I got the element Q42 using "element = j[4]", the code "element["claims"]["P31"]" provides me with an array of wikidata entities. However, what I'm supposed to get is an object of Q5. (Q42 is supposed to be connected to Q5 with P31)

I'm wondering whether the reading method follows the original json file structure exactly?

**Comment by henu** [comment]
Hi! Sorry for the long response time.

I made some fixes to Array type, could you please test if the problem still exists?

If the bug is still there, could you show me where I can download the JSON file and your code that is trying to read it.

**Comment by jackyys** [comment]
Fixed, thanks.
