### ISSUE TITLE
Error parsing JSON file

### ISSUE THREAD

**Issue by ssic7i** [henu/bigjson#13]
I'm trying parse big json file and getting error "Exception: Unexpected bytes!"
Similar json structure and code in attachment.
In test script it raising at line 5 in my code (  print(json_obj['nested_list1'])  )

Built-in json library parsing this file structure successfully.
Could you please help me with it?
[bigjson_test.zip](https://github.com/henu/bigjson/files/5028492/bigjson_test.zip)

**Comment by henu** [comment]
Should be fixed now. The library was confused because of Windows line terminators in the JSON file.

Thanks for your bug report and good test data!
