### ISSUE TITLE
UnicodeEncodeError: 'unicodeescape' codec can't decode bytes in position 7-9: truncated \UXXXXXXXX escape

### ISSUE THREAD

**Issue by Xccanxin** [henu/bigjson#17]
hi henu,it is a nice work for reading big json file. I am working with same wiki data as your example.

import bigjson
with open('wikidata-latest-all.json', 'rb') as f:
    j = bigjson.load(f)
    element = j[4]

But when the index of j becomes larger(2000+),there comes the error as mentioned.
I tried to change the original code in filereader line 119 
string = string.decode('unicode_escape').encode('utf-16', 'surrogatepass').decode('utf-16')
to
string = string.decode('utf-8')
and it worked

so everytime i want to read new data, i need to change the encoding manually.
is there a quick way to add the param to load() funtion

**Comment by henu** [comment]
Assume this is fixed now, so closing it.
