### ISSUE TITLE
Numpy, Pandas support? 

### ISSUE THREAD

**Issue by mertbozkir** [henu/bigjson#19]
Hey, I'm trying to handle a 14Gb JSON file. This bigjson is so great to handle this dataset. But I want to work with Numpy and Pandas. Is there any way to convert `bigjson.array.Array` to `pd.DataFrame` or `np.Array?`

**Comment by henu** [comment]
There is no direct support for numpy/pandas. The only method is to manually iterate those arrays and form numpy/pandas arrays from them.

**Comment by alexhoule2** [comment]
@henu 
I like the interface it's nice and simple
How would it perform vs streaming a library like ijson?
