### ISSUE TITLE
Import but said: "ModuleNotFoundError: No module named 'filereader"

### ISSUE THREAD

**Issue by zychen423** [henu/bigjson#4]
Hi, first of all, thanks for providing this tool. I find it by series of SO.

However, I cannot use it in my code. I said `ModuleNotFoundError: No module named 'filereader` when I tried to import it. The whole ipython looks like:

```python
$ :~ ipython3
Python 3.6.3 (default, Oct  6 2017, 00:00:00)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import bigjson
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-dc600f1cd09e> in <module>()
----> 1 import bigjson

/usr/local/lib/python3.6/dist-packages/bigjson-1.0-py3.6.egg/bigjson/__init__.py in <module>()
----> 1 from filereader import FileReader
      2
      3
      4 def load(file):
      5     reader = FileReader(file)

ModuleNotFoundError: No module named 'filereader'
```

I install this module by
```
$:~ cd bigjson
$:~/bigjson sudo python3.6 setup.py install
```

Is there anything wrong with my installation?

**Comment by mmmilja** [comment]
Hi all,

I am having the same issue as zychen423, I am getting the "ModuleNotFoundError: No module named 'filereader'" error. I can see that filereader.py does exist in the bigjson folder of the GitHub zip I used to install the library.

Any ideas as to how to fix this error?

**Comment by zychen423** [comment]
@mmmilja so does python2 work?

**Comment by henu** [comment]
Should be fixed now. Closing issue.
