### ISSUE TITLE
Error: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5693: ordinal not in range(128)

### ISSUE THREAD

**Issue by maedo** [henu/bigjson#7]
Hi, when run 

with open(file, mode='rb') as jsonfile:
    jsonData = bigjson.load(jsonfile)

get the follow error:

UnicodeDecodeError                        Traceback (most recent call last)

<ipython-input-34-aa7c0479dc13> in <module>()
      4 
      5 with open(file, mode='rb') as jsonfile:
----> 6     jsonData = bigjson.load(jsonfile)

3 frames

/usr/local/lib/python3.6/dist-packages/bigjson/__init__.py in load(file)
      4 def load(file):
      5     reader = FileReader(file)
----> 6     return reader.read()

/usr/local/lib/python3.6/dist-packages/bigjson/filereader.py in read(self, read_all, to_python)
     20         assert read_all or not to_python
     21 
---> 22         self._skip_whitespace()
     23 
     24         # None

/usr/local/lib/python3.6/dist-packages/bigjson/filereader.py in _skip_whitespace(self)
    134     def _skip_whitespace(self):
    135         while True:
--> 136             self._ensure_readbuf_left(1)
    137             if len(self.readbuf) - self.readbuf_read < 1:
    138                 break

/usr/local/lib/python3.6/dist-packages/bigjson/filereader.py in _ensure_readbuf_left(self, minimum_left)
    188         read_amount = max(minimum_left, FileReader._READBUF_CHUNK_SIZE) - (len(self.readbuf) - self.readbuf_read)
    189         self.readbuf_pos += self.readbuf_read
--> 190         self.readbuf = self.readbuf[self.readbuf_read:] + self.file.read(read_amount).decode('ascii')
    191         self.readbuf_read = 0
    192 

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5693: ordinal not in range(128)

**Comment by henu** [comment]
Can you provide the JSON file that is causing this problem?

**Comment by BarbaraFons** [comment]
Hi, have the same problem can anyone help me? 

import bigjson
with open('20191115.json', 'rb') as OTDR:    #  I tried also with "mode='rb' " and is the same issue
    dfj = bigjson.load(OTDR)

The error message is:

---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-2-b503e0cdd420> in <module>
      1 import json
      2 with open('20191115.json') as OTDR:
----> 3     dfj = json.load(OTDR)
      4 #     element = j[5]
      5 #     print (element['_id'])

~\Anaconda3\envs\snakes\lib\json\__init__.py in load(fp, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    291     kwarg; otherwise ``JSONDecoder`` is used.
    292     """
--> 293     return loads(fp.read(),
    294         cls=cls, object_hook=object_hook,
    295         parse_float=parse_float, parse_int=parse_int,

~\Anaconda3\envs\snakes\lib\encodings\cp1252.py in decode(self, input, final)
     21 class IncrementalDecoder(codecs.IncrementalDecoder):
     22     def decode(self, input, final=False):
---> 23         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
     24 
     25 class StreamWriter(Codec,codecs.StreamWriter):

MemoryError:

**Comment by henu** [comment]
@BarbaraFons in your code you say `import json`.

**Comment by MapleCCC** [comment]
Encountered similar probelm. I guess the reason is that bigjson by default assume file should be decoded by ASCII. The assumption is seen from the following [line](https://github.com/henu/bigjson/blob/142d7b07ca82dd46b40b1fa52f884830d6489a67/bigjson/filereader.py#L190):

```python
self.readbuf = self.readbuf[self.readbuf_read:] + self.file.read(read_amount).decode('ascii')
```

Perhaps adopting a more widely-used encoding schem like UTF-8 can solve the problem?

**Comment by BarbaraFons** [comment]
Thank you for your help I will try both.

**Comment by nongiach** [comment]
yes, same problem here bigjson doesn't see to handle UTF8

**Comment by henu** [comment]
There has been quite many improvements since this issue, so I assume this is now fixed. Please send examples if it still doesn't work.
